# many settings are copied verbatim from mkdocs-material
# https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml

site_name: The Internals of Spark SQL
site_url: https://books.japila.pl/spark-sql-internals
site_author: Jacek Laskowski

docs_dir: mkdocs

repo_name: mastering-spark-sql-book
repo_url: https://github.com/jaceklaskowski/mastering-spark-sql-book
edit_uri: ""

copyright: Copyright &copy; 2020 Jacek Laskowski

theme:
  name: 'material'
  language: en
  features:
    - tabs
    - instant

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  # this doesn't seem to work on ReadTheDocs
  # https://github.com/readthedocs/readthedocs.org/issues/6889
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
  # - git-revision-date-localized:
  #     type: date
  - awesome-pages

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/jaceklaskowski
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jaceklaskowski
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jaceklaskowski

nav:
  - Home:
    - index.md
    - spark-sql.md
    - spark-sql-dataset-rdd.md
    - spark-sql-dataset-vs-sql.md
    - Developing Applications: spark-sql-fundamentals-spark-application-development.md
    - SparkSession:
      - spark-sql-SparkSession.md
      - spark-sql-SparkSession-Builder.md
      - spark-sql-SparkSession-implicits.md
      - spark-sql-SparkSessionExtensions.md
    - Dataset:
      - spark-sql-Dataset.md
      - Encoder:
        - spark-sql-Encoder.md
        - spark-sql-Encoders.md
        - spark-sql-ExpressionEncoder.md
        - spark-sql-RowEncoder.md
        - spark-sql-ExpressionEncoder-LocalDateTime.md
      - spark-sql-DataFrame.md
      - spark-sql-Row.md
    - spark-sql-datasource-api.md
    - spark-sql-DataFrameReader.md
    - spark-sql-DataFrameWriter.md
    - Dataset API:
      - spark-sql-dataset-operators.md
      - spark-sql-Dataset-typed-transformations.md
      - spark-sql-Dataset-untyped-transformations.md
      - spark-sql-Dataset-basic-actions.md
      - spark-sql-Dataset-actions.md
      - spark-sql-DataFrameNaFunctions.md
      - spark-sql-DataFrameStatFunctions.md
    - Column:
      - spark-sql-Column.md
      - spark-sql-column-operators.md
      - spark-sql-TypedColumn.md
    - Basic Aggregation:
      - spark-sql-basic-aggregation.md
      - spark-sql-RelationalGroupedDataset.md
      - spark-sql-KeyValueGroupedDataset.md
    - Joins:
      - spark-sql-joins.md
      - spark-sql-joins-broadcast.md
    - Window Aggregation:
      - spark-sql-window-aggregation.md
      - spark-sql-WindowSpec.md
      - spark-sql-WindowSpec-Window.md
    - Standard Functions:
      - spark-sql-functions.md
      - spark-sql-aggregate-functions.md
      - spark-sql-functions-collection.md
      - spark-sql-functions-datetime.md
      - spark-sql-functions-regular-functions.md
      - spark-sql-functions-windows.md
    - User-Defined Functions:
      - spark-sql-udfs.md
      - spark-sql-udfs-blackbox.md
      - spark-sql-UserDefinedFunction.md
    - Schema:
      - spark-sql-schema.md
      - spark-sql-StructType.md
      - spark-sql-StructField.md
      - spark-sql-DataType.md
    - spark-sql-multi-dimensional-aggregation.md
    - Caching and Persistence:
      - spark-sql-caching-and-persistence.md
      - spark-sql-caching-webui-storage.md
    - spark-sql-checkpointing.md
    - spark-sql-UserDefinedAggregateFunction.md
    - spark-sql-Aggregator.md
    - spark-sql-properties.md
  - Notable Features:
    - spark-sql-hive-integration.md
    - spark-sql-vectorized-parquet-reader.md
    - spark-sql-dynamic-partition-inserts.md
    - spark-sql-bucketing.md
    - Whole-Stage CodeGen:
      - spark-sql-whole-stage-codegen.md
      - spark-sql-CodegenContext.md
      - spark-sql-CodeGenerator.md
      - spark-sql-GenerateColumnAccessor.md
      - spark-sql-GenerateOrdering.md
      - spark-sql-GeneratePredicate.md
      - spark-sql-GenerateSafeProjection.md
      - spark-sql-BytesToBytesMap.md
      - Subexpression Elimination:
        - spark-sql-subexpression-elimination.md
        - spark-sql-EquivalentExpressions.md
    - Vectorized Query Execution:
      - spark-sql-vectorized-query-execution.md
      - spark-sql-ColumnarBatch.md
    - spark-sql-data-source-api-v2.md
    - spark-sql-subqueries.md
    - spark-sql-hint-framework.md
    - Adaptive Query Execution:
      - spark-sql-adaptive-query-execution.md
      - spark-sql-ExchangeCoordinator.md
    - Cost-Based Optimization:
      - spark-sql-cost-based-optimization.md
      - spark-sql-CatalogStatistics.md
      - spark-sql-ColumnStat.md
      - spark-sql-EstimationUtils.md
      - spark-sql-CommandUtils.md
    - spark-sql-catalyst-dsl.md
  - Tools:
    - tools/spark-sql-spark-sql.md
  - Hive:
    - hive/index.md
    - hive/configuration-properties.md
    - hive/spark-sql-hive-metastore.md
    - hive/spark-sql-DataSinks.md
    - hive/HiveFileFormat.md
    - HiveClient:
      - hive/HiveClient.md
      - hive/HiveClientImpl.md
    - hive/HiveUtils.md
    - hive/IsolatedClientLoader.md
    - hive/HiveTableRelation.md
    - hive/CreateHiveTableAsSelectCommand.md
    - hive/SaveAsHiveFile.md
    - hive/InsertIntoHiveDirCommand.md
    - hive/InsertIntoHiveTable.md
    - hive/HiveTableScans.md
    - hive/HiveTableScanExec.md
    - hive/TableReader.md
    - hive/HadoopTableReader.md
    - hive/HiveSessionStateBuilder.md
    - hive/HiveExternalCatalog.md
    - hive/HiveSessionCatalog.md
    - hive/HiveMetastoreCatalog.md
    - hive/RelationConversions.md
    - hive/ResolveHiveSerdeTable.md
    - hive/DetermineTableStats.md
    - hive/HiveAnalysis.md
  - Demos:
    - demo/demo-connecting-spark-sql-to-hive-metastore.md
    - demo/demo-hive-partitioned-parquet-table-partition-pruning.md
